### ISSUE TITLE
Support MinkUNet ?

### ISSUE THREAD

**Issue by chenhaomingbob** [valeoai/ScaLR#1]
Hi authors, thanks for your wonderful work!
Do you have the config for MinkUNet? The MinkUNet is usually selected as the backbone in 3D pre-training.

**Comment by gpuy** [comment]
Hi, 

thank you for your interest in this repo.

One takeaway of our work is that the choice of student and teacher networks has a huge impact on the quality of the distilled features.

In particular, we obtain better results with WaffleIron than with MinkUnet. We released the best performing setup. It is also easier to maintain: WaffleIron only needs pytorch installed; no other external library for sparse convolution is required. 

If you want to pretrain a MinkUnet, you can check our former work: SLidR (https://github.com/valeoai/SLidR).

Cheers,

Gilles

**Comment by chenhaomingbob** [comment]
thanks ~
